apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: thanos-receive-default
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/version: v0.17.2
    controller.receive.thanos.io/hashring: default
  name: thanos-receive-default
  namespace: thanos
spec:
  endpoints:
  - port: http
    relabelings:
    - separator: /
      sourceLabels:
      - namespace
      - pod
      targetLabel: instance
  selector:
    matchLabels:
      app.kubernetes.io/component: database-write-hashring
      app.kubernetes.io/instance: thanos-receive-default
      app.kubernetes.io/name: thanos-receive
      controller.receive.thanos.io/hashring: default
